ABBREVIATION_DICT_LOWERCASE = {
    # Business & Government
    "ceo": "chief executive officer",
    "coo": "chief operating officer",
    "cfo": "chief financial officer",
    "hr": "human resources",
    "it": "information technology",
    "r&d": "research and development",
    "ngo": "non-governmental organization",
    "usa": "united states of america",
    "eu": "european union",
    "un": "united nations",
    "fbi": "federal bureau of investigation",
    "cia": "central intelligence agency",
    # Technology & Science
    "ai": "artificial intelligence",
    "ml": "machine learning",
    "nlp": "natural language processing",
    "api": "application programming interface",
    "url": "uniform resource locator",
    "http": "hypertext transfer protocol",
    "ftp": "file transfer protocol",
    "ram": "random access memory",
    "cpu": "central processing unit",
    "nasa": "national aeronautics and space administration",
    # Education
    "phd": "doctor of philosophy",
    "mba": "master of business administration",
    "bsc": "bachelor of science",
    "ba": "bachelor of arts",
    "ma": "master of arts",
    "msc": "master of science",
    # Medicine & Health
    "md": "doctor of medicine",
    "do": "doctor of osteopathic medicine",
    "icu": "intensive care unit",
    "mri": "magnetic resonance imaging",
    "ct": "computed tomography",
    "covid-19": "coronavirus disease 2019",
    # Common Terms
    "e.g.": "exempli gratia",
    "i.e.": "id est",
    "etc.": "et cetera",
    "vs": "versus",
    "rip": "rest in peace",
    "fyi": "for your information",
    "asap": "as soon as possible",
    "lol": "laughing out loud",
    "brb": "be right back",
    "idk": "i don't know",
    "imo": "in my opinion",
    "tba": "to be announced",
    "tbd": "to be determined",
    "eta": "estimated time of arrival",
}
